### ISSUE TITLE
How to ommit pogreb output before the result of get ?

### ISSUE THREAD

**Issue by waldirborbajr** [akrylysov/pogreb#51]
How to ommit this pogreb output before get my result?

❯ go run main.go getkv prm2
pogreb: moving non-segment files...
pogreb: moved 00000-1.psg.pmt to 00000-1.psg.pmt.bac
pogreb: moved db.pmt to db.pmt.bac
pogreb: moved index.pmt to index.pmt.bac
pogreb: moved main.pix to main.pix.bac
pogreb: moved overflow.pix to overflow.pix.bac
pogreb: error reading segment meta 0: EOF
pogreb: started recovery
pogreb: rebuilding index...
pogreb: removing recovery backup files...
pogreb: removed 00000-1.psg.pmt.bac
pogreb: removed db.pmt.bac
pogreb: removed index.pmt.bac
pogreb: removed main.pix.bac
pogreb: removed overflow.pix.bac
pogreb: successfully recovered database
conten123Test

**Comment by akrylysov** [comment]
Hi,

You can redirect the logger output using [pogreb.SetLogger](https://pkg.go.dev/github.com/akrylysov/pogreb#SetLogger). 
If you want to disable the logging entirely you can do `pogreb.SetLogger(log.New(ioutil.Discard, "", 0))`.

Rather than disabling logging, I would fix the cause of the recovery log lines. Most likely the database is not closed before the process exists - `db.Close` is not called, which triggers recovery the next time the database is opened.
